--
-- PostgreSQL database dump
--

\restrict HNdliL8SFWn7G4odm2bWH0GUj2Sp2kE27Ork59x1qc1Kb5lROh46JtaVRzViV60

-- Dumped from database version 16.15
-- Dumped by pg_dump version 16.15

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: pg_trgm; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;


--
-- Name: EXTENSION pg_trgm; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION pg_trgm IS 'text similarity measurement and index searching based on trigrams';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: app_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_user (
    id bigint NOT NULL,
    partner_id bigint,
    email character varying(255),
    name character varying(255),
    password character varying(255),
    role character varying(255),
    CONSTRAINT app_user_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying, 'ADMIN_MARKET'::character varying, 'COURIER'::character varying, 'SELLER'::character varying, 'ORGANIZER'::character varying, 'SERVICE_PROVIDER'::character varying, 'PARTNER'::character varying, 'ADMIN_DELIVERY'::character varying, 'RECRUITER'::character varying, 'EVENT'::character varying])::text[])))
);


--
-- Name: app_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: application; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.application (
    is_flagged boolean,
    matching_score double precision NOT NULL,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    job_offer_id bigint NOT NULL,
    last_candidate_action_at timestamp(6) without time zone,
    user_id bigint NOT NULL,
    activity_status character varying(255),
    experience_level character varying(255),
    field_of_study character varying(255),
    motivation text,
    status character varying(255) NOT NULL,
    years_of_experience character varying(255),
    CONSTRAINT application_activity_status_check CHECK (((activity_status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'AT_RISK'::character varying])::text[]))),
    CONSTRAINT application_experience_level_check CHECK (((experience_level)::text = ANY ((ARRAY['BEGINNER'::character varying, 'INTERMEDIATE'::character varying, 'ADVANCED'::character varying])::text[])))
);


--
-- Name: application_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.application ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.application_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: application_languages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.application_languages (
    application_id bigint NOT NULL,
    languages character varying(255)
);


--
-- Name: application_skills; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.application_skills (
    application_id bigint NOT NULL,
    skills character varying(255)
);


--
-- Name: booking; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.booking (
    duration double precision NOT NULL,
    priority_markup numeric(10,2),
    total_price numeric(10,2),
    created_at timestamp(6) without time zone,
    date timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    id bigint NOT NULL,
    partner_id bigint,
    project_id bigint,
    provider_id bigint,
    service_id bigint,
    updated_at timestamp(6) without time zone,
    user_id bigint,
    notes character varying(255),
    status character varying(255),
    CONSTRAINT booking_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PENDING_EVALUATION'::character varying, 'TENTATIVE'::character varying, 'APPROVED'::character varying, 'CONFIRMED'::character varying, 'REJECTED'::character varying, 'IN_PROGRESS'::character varying, 'PENDING_REVIEW'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying, 'DISPUTED'::character varying])::text[])))
);


--
-- Name: booking_attachment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.booking_attachment (
    booking_id bigint NOT NULL,
    file_size bigint,
    id bigint NOT NULL,
    uploaded_at timestamp(6) without time zone NOT NULL,
    uploaded_by bigint NOT NULL,
    file_name character varying(255) NOT NULL,
    file_type character varying(255),
    file_url character varying(255) NOT NULL
);


--
-- Name: booking_attachment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.booking_attachment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.booking_attachment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: booking_audit_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.booking_audit_log (
    booking_id bigint NOT NULL,
    changed_at timestamp(6) without time zone NOT NULL,
    changed_by bigint,
    id bigint NOT NULL,
    from_status character varying(255),
    to_status character varying(255) NOT NULL
);


--
-- Name: booking_audit_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.booking_audit_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.booking_audit_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: booking_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.booking ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.booking_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: booking_message; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.booking_message (
    booking_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    sender_id bigint NOT NULL,
    message text NOT NULL
);


--
-- Name: booking_message_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.booking_message ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.booking_message_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: category; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.category (
    id bigint NOT NULL,
    store_id bigint,
    description character varying(255),
    name character varying(255)
);


--
-- Name: category_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: collaboration; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.collaboration (
    event_id bigint,
    id bigint NOT NULL,
    description text,
    name character varying(255) NOT NULL,
    type character varying(255) NOT NULL
);


--
-- Name: collaboration_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.collaboration ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.collaboration_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: courier; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.courier (
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    interview_date timestamp(6) without time zone,
    user_id bigint NOT NULL,
    permit_content_type character varying(255),
    permit_file_name character varying(255),
    phone_number character varying(255),
    profile_status character varying(255),
    status character varying(255) NOT NULL,
    permit_image bytea,
    CONSTRAINT courier_profile_status_check CHECK (((profile_status)::text = ANY ((ARRAY['INCOMPLETE'::character varying, 'COMPLETED'::character varying])::text[]))),
    CONSTRAINT courier_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'ACCEPTED'::character varying, 'REFUSED'::character varying])::text[])))
);


--
-- Name: courier_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.courier ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courier_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: deliverable; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.deliverable (
    version integer NOT NULL,
    booking_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    deleted_at timestamp(6) without time zone,
    id bigint NOT NULL,
    provider_id bigint NOT NULL,
    reviewed_at timestamp(6) without time zone,
    submitted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    description character varying(2000),
    status character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    CONSTRAINT deliverable_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'SUBMITTED'::character varying, 'ACCEPTED'::character varying, 'REVISION_REQUESTED'::character varying, 'REJECTED'::character varying])::text[])))
);


--
-- Name: deliverable_attachment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.deliverable_attachment (
    deliverable_id bigint NOT NULL,
    file_size bigint,
    id bigint NOT NULL,
    uploaded_at timestamp(6) without time zone NOT NULL,
    file_name character varying(255) NOT NULL,
    file_type character varying(255),
    file_url character varying(255) NOT NULL
);


--
-- Name: deliverable_attachment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.deliverable_attachment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.deliverable_attachment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: deliverable_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.deliverable ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.deliverable_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: deliverable_review; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.deliverable_review (
    deliverable_id bigint NOT NULL,
    id bigint NOT NULL,
    reviewed_at timestamp(6) without time zone NOT NULL,
    reviewer_id bigint NOT NULL,
    comment character varying(2000),
    decision character varying(255) NOT NULL,
    CONSTRAINT deliverable_review_decision_check CHECK (((decision)::text = ANY ((ARRAY['ACCEPTED'::character varying, 'REVISION_REQUESTED'::character varying, 'REJECTED'::character varying])::text[])))
);


--
-- Name: deliverable_review_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.deliverable_review ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.deliverable_review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: deliverable_version; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.deliverable_version (
    version_number integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    deliverable_id bigint NOT NULL,
    id bigint NOT NULL,
    reviewed_at timestamp(6) without time zone,
    submitted_at timestamp(6) without time zone,
    status character varying(255) NOT NULL,
    CONSTRAINT deliverable_version_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'SUBMITTED'::character varying, 'ACCEPTED'::character varying, 'REVISION_REQUESTED'::character varying, 'REJECTED'::character varying])::text[])))
);


--
-- Name: deliverable_version_attachment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.deliverable_version_attachment (
    deliverable_version_id bigint NOT NULL,
    file_size bigint,
    id bigint NOT NULL,
    uploaded_at timestamp(6) without time zone NOT NULL,
    file_name character varying(255) NOT NULL,
    file_type character varying(255),
    file_url character varying(255) NOT NULL
);


--
-- Name: deliverable_version_attachment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.deliverable_version_attachment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.deliverable_version_attachment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: deliverable_version_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.deliverable_version ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.deliverable_version_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: delivery; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.delivery (
    base_order_amount numeric(10,3),
    distance_km numeric(10,3),
    height numeric(10,3),
    length numeric(10,3),
    real_weight numeric(10,3),
    width numeric(10,3),
    address_details_id bigint,
    connected_user_id bigint,
    deliverydate timestamp(6) without time zone,
    id bigint NOT NULL,
    order_id bigint,
    tracking_id bigint,
    vehicule_id bigint,
    address character varying(255),
    cancellation_reason character varying(255),
    city character varying(255),
    delivery_address character varying(255),
    delivery_mode character varying(255),
    deliverytype character varying(255),
    payment_mode character varying(255),
    phone_number character varying(255),
    postal_code character varying(255),
    qr_token character varying(255),
    status character varying(255),
    CONSTRAINT delivery_delivery_mode_check CHECK (((delivery_mode)::text = ANY ((ARRAY['LIVRAISON_A_DOMICILE'::character varying, 'RETRAIT_A_ESPRIT'::character varying])::text[]))),
    CONSTRAINT delivery_payment_mode_check CHECK (((payment_mode)::text = ANY ((ARRAY['CHEQUE'::character varying, 'ESPECE_A_LA_LIVRAISON'::character varying, 'CARTE_BANCAIRE'::character varying])::text[])))
);


--
-- Name: delivery_address_details; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.delivery_address_details (
    connected_user_id bigint,
    id bigint NOT NULL,
    city character varying(255),
    delivery_address character varying(255),
    phone_number character varying(255),
    postal_code character varying(255)
);


--
-- Name: delivery_address_details_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.delivery_address_details ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.delivery_address_details_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: delivery_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.delivery ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.delivery_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dispute_mediation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dispute_mediation (
    suggested_deadline_extension_days integer,
    suggested_refund_percent double precision,
    booking_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    resolved_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    client_vote character varying(50),
    provider_vote character varying(50),
    status character varying(50) NOT NULL,
    suggested_resolution character varying(50) NOT NULL,
    analysis_summary character varying(1000),
    CONSTRAINT dispute_mediation_client_vote_check CHECK (((client_vote)::text = ANY ((ARRAY['ACCEPT'::character varying, 'REJECT'::character varying, 'ABSTAIN'::character varying])::text[]))),
    CONSTRAINT dispute_mediation_provider_vote_check CHECK (((provider_vote)::text = ANY ((ARRAY['ACCEPT'::character varying, 'REJECT'::character varying, 'ABSTAIN'::character varying])::text[]))),
    CONSTRAINT dispute_mediation_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'IN_PROGRESS'::character varying, 'RESOLVED'::character varying, 'ESCALATED'::character varying])::text[]))),
    CONSTRAINT dispute_mediation_suggested_resolution_check CHECK (((suggested_resolution)::text = ANY ((ARRAY['PARTIAL_REFUND'::character varying, 'FULL_REFUND'::character varying, 'EXTEND_DEADLINE'::character varying, 'REASSIGN_PROVIDER'::character varying, 'NO_ACTION'::character varying])::text[])))
);


--
-- Name: dispute_mediation_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.dispute_mediation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dispute_mediation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: equipment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.equipment (
    quantity integer DEFAULT 1 NOT NULL,
    event_id bigint,
    id bigint NOT NULL,
    image_url text,
    name character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    type character varying(255) NOT NULL
);


--
-- Name: equipment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.equipment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.equipment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: equipment_reservation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.equipment_reservation (
    quantity integer NOT NULL,
    equipment_id bigint,
    id bigint NOT NULL,
    reservation_id bigint,
    stall_id bigint
);


--
-- Name: equipment_reservation_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.equipment_reservation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.equipment_reservation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: escrow_hold; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.escrow_hold (
    amount double precision NOT NULL,
    booking_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    release_deadline timestamp(6) without time zone,
    released_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    wallet_id bigint NOT NULL,
    status character varying(30) NOT NULL
);


--
-- Name: escrow_hold_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.escrow_hold ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.escrow_hold_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: event; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.event (
    date date NOT NULL,
    nb_tickets integer DEFAULT 0 NOT NULL,
    online boolean NOT NULL,
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    location character varying(255) NOT NULL,
    meeting_link character varying(255),
    name character varying(255) NOT NULL,
    status character varying(50) DEFAULT 'UPCOMING'::character varying NOT NULL
);


--
-- Name: event_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.event ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: interview; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.interview (
    application_id bigint NOT NULL,
    id bigint NOT NULL,
    interview_date timestamp(6) without time zone NOT NULL,
    location character varying(255),
    result character varying(255),
    result_notes text,
    status character varying(255) DEFAULT 'SCHEDULED'::character varying,
    type character varying(255) NOT NULL,
    CONSTRAINT interview_result_check CHECK (((result)::text = ANY ((ARRAY['ACCEPTED'::character varying, 'REJECTED'::character varying, 'WAITING_LIST'::character varying])::text[]))),
    CONSTRAINT interview_status_check CHECK (((status)::text = ANY ((ARRAY['SCHEDULED'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[])))
);


--
-- Name: interview_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.interview ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.interview_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: job_offer; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.job_offer (
    company_id bigint NOT NULL,
    id bigint NOT NULL,
    description text,
    experience_level character varying(255) NOT NULL,
    location character varying(255) NOT NULL,
    required_skills text,
    status character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    CONSTRAINT job_offer_experience_level_check CHECK (((experience_level)::text = ANY ((ARRAY['BEGINNER'::character varying, 'INTERMEDIATE'::character varying, 'ADVANCED'::character varying])::text[])))
);


--
-- Name: job_offer_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.job_offer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.job_offer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: map_tracking; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.map_tracking (
    estimated_arrival timestamp(6) without time zone,
    id bigint NOT NULL,
    last_update timestamp(6) without time zone,
    current_location character varying(255)
);


--
-- Name: map_tracking_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.map_tracking ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.map_tracking_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.messages (
    read boolean NOT NULL,
    id bigint NOT NULL,
    sent_at timestamp(6) without time zone NOT NULL,
    content character varying(2000) NOT NULL,
    receiver_id character varying(255) NOT NULL,
    sender_id character varying(255) NOT NULL
);


--
-- Name: messages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: milestone_bookings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.milestone_bookings (
    booking_id bigint NOT NULL,
    milestone_id bigint NOT NULL
);


--
-- Name: milestone_services; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.milestone_services (
    estimated_hours double precision,
    milestone_id bigint NOT NULL,
    service_id bigint NOT NULL
);


--
-- Name: notification; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notification (
    is_read boolean NOT NULL,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    read_at timestamp(6) without time zone,
    recipient_id bigint NOT NULL,
    related_entity_id bigint,
    related_entity_type character varying(50),
    type character varying(50) NOT NULL,
    title character varying(200) NOT NULL,
    message character varying(2000),
    priority character varying(255) NOT NULL
);


--
-- Name: notification_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_lines; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_lines (
    price double precision,
    quantity integer NOT NULL,
    subtotal double precision,
    weight double precision,
    id bigint NOT NULL,
    order_id bigint,
    product_id bigint,
    dimensions_label character varying(255)
);


--
-- Name: order_lines_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.order_lines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_lines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.orders (
    total_amount double precision,
    date timestamp(6) without time zone,
    id bigint NOT NULL,
    user_id bigint,
    payment_method character varying(255),
    status character varying(255)
);


--
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: partner; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.partner (
    deleted_at timestamp(6) without time zone,
    id bigint NOT NULL,
    contact_info character varying(255),
    name character varying(255),
    role character varying(255),
    CONSTRAINT partner_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying, 'ADMIN_MARKET'::character varying, 'COURIER'::character varying, 'SELLER'::character varying, 'ORGANIZER'::character varying, 'SERVICE_PROVIDER'::character varying, 'PARTNER'::character varying, 'ADMIN_DELIVERY'::character varying, 'RECRUITER'::character varying, 'EVENT'::character varying])::text[])))
);


--
-- Name: partner_company; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.partner_company (
    id bigint NOT NULL,
    contact_email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    partnership_status character varying(255) NOT NULL,
    sector character varying(255)
);


--
-- Name: partner_company_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.partner_company ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.partner_company_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: partner_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.partner ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.partner_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: partner_projects; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.partner_projects (
    partner_id bigint NOT NULL,
    project_id bigint NOT NULL
);


--
-- Name: partner_services; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.partner_services (
    partner_id bigint NOT NULL,
    service_id bigint NOT NULL
);


--
-- Name: partnership_notification; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.partnership_notification (
    is_read boolean,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    message text NOT NULL,
    type character varying(255) NOT NULL,
    CONSTRAINT partnership_notification_type_check CHECK (((type)::text = ANY ((ARRAY['APPLICATION'::character varying, 'INTERVIEW_REMINDER'::character varying, 'RESULT'::character varying])::text[])))
);


--
-- Name: partnership_notification_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.partnership_notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.partnership_notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: password_reset_code; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.password_reset_code (
    used boolean NOT NULL,
    code character varying(5) NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    email character varying(255) NOT NULL
);


--
-- Name: password_reset_code_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.password_reset_code ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.password_reset_code_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product (
    discount_percent double precision,
    original_price double precision,
    price double precision,
    stock integer,
    weight double precision,
    category_id bigint,
    id bigint NOT NULL,
    promo_end_at timestamp(6) without time zone,
    promo_start_at timestamp(6) without time zone,
    store_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    status character varying(30),
    description character varying(255),
    dimensions_label character varying(255),
    image_url text,
    name character varying(255),
    CONSTRAINT product_check CHECK ((((promo_start_at IS NULL) AND (promo_end_at IS NULL)) OR ((promo_start_at IS NOT NULL) AND (promo_end_at IS NOT NULL) AND (promo_end_at > promo_start_at)))),
    CONSTRAINT product_discount_percent_check CHECK (((discount_percent IS NULL) OR ((discount_percent > (0)::double precision) AND (discount_percent <= (100)::double precision))))
);


--
-- Name: product_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_users (
    product_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: profil; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profil (
    id bigint NOT NULL,
    user_id bigint,
    experience_level character varying(255),
    field_of_study character varying(255),
    years_of_experience character varying(255),
    CONSTRAINT profil_experience_level_check CHECK (((experience_level)::text = ANY ((ARRAY['BEGINNER'::character varying, 'INTERMEDIATE'::character varying, 'ADVANCED'::character varying])::text[])))
);


--
-- Name: profil_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.profil ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.profil_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: profil_languages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profil_languages (
    profil_id bigint NOT NULL,
    languages character varying(255)
);


--
-- Name: profil_skills; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profil_skills (
    profil_id bigint NOT NULL,
    skills character varying(255)
);


--
-- Name: project; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.project (
    budget numeric(12,2),
    creator_id bigint,
    deleted_at timestamp(6) without time zone,
    end_date timestamp(6) without time zone,
    estimated_end_date timestamp(6) without time zone,
    id bigint NOT NULL,
    start_date timestamp(6) without time zone,
    details character varying(255),
    priority character varying(255),
    status character varying(255),
    title character varying(255),
    CONSTRAINT project_status_check CHECK (((status)::text = ANY ((ARRAY['PLANNED'::character varying, 'IN_PROGRESS'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[])))
);


--
-- Name: project_dependency; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.project_dependency (
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    predecessor_milestone_id bigint NOT NULL,
    project_id bigint NOT NULL,
    successor_milestone_id bigint NOT NULL
);


--
-- Name: project_dependency_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.project_dependency ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.project_dependency_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: project_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.project ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.project_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: project_milestone; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.project_milestone (
    sort_order integer NOT NULL,
    actual_end_date timestamp(6) without time zone,
    actual_start_date timestamp(6) without time zone,
    assigned_provider_id bigint,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    id bigint NOT NULL,
    planned_end_date timestamp(6) without time zone,
    planned_start_date timestamp(6) without time zone,
    project_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    original_details character varying(150),
    original_title character varying(150),
    title character varying(150) NOT NULL,
    condition_expression character varying(500),
    handoff_notes character varying(500),
    details text,
    milestone_type character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    CONSTRAINT project_milestone_milestone_type_check CHECK (((milestone_type)::text = ANY ((ARRAY['MILESTONE'::character varying, 'CONDITION'::character varying, 'START'::character varying, 'END'::character varying])::text[]))),
    CONSTRAINT project_milestone_status_check CHECK (((status)::text = ANY ((ARRAY['PLANNED'::character varying, 'IN_PROGRESS'::character varying, 'COMPLETED'::character varying, 'BLOCKED'::character varying, 'CANCELLED'::character varying])::text[])))
);


--
-- Name: project_milestone_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.project_milestone ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.project_milestone_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: project_services; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.project_services (
    project_id bigint NOT NULL,
    service_id bigint NOT NULL
);


--
-- Name: project_users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.project_users (
    project_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: provider_exception; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.provider_exception (
    date date NOT NULL,
    end_hour time(0) without time zone,
    start_hour time(0) without time zone,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    provider_id bigint,
    updated_at timestamp(6) without time zone,
    reason character varying(255),
    type character varying(255) NOT NULL,
    CONSTRAINT provider_exception_type_check CHECK (((type)::text = ANY ((ARRAY['BLOCKED'::character varying, 'CUSTOM_HOURS'::character varying])::text[])))
);


--
-- Name: provider_exception_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.provider_exception ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.provider_exception_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: provider_mandate; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.provider_mandate (
    max_bookings integer NOT NULL,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    provider_id bigint,
    updated_at timestamp(6) without time zone
);


--
-- Name: provider_mandate_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.provider_mandate ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.provider_mandate_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: provider_weekly_template; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.provider_weekly_template (
    end_hour time(0) without time zone NOT NULL,
    max_concurrent integer NOT NULL,
    slot_duration_minutes integer NOT NULL,
    start_hour time(0) without time zone NOT NULL,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    provider_id bigint,
    service_id bigint,
    updated_at timestamp(6) without time zone,
    day_of_week character varying(255) NOT NULL,
    CONSTRAINT provider_weekly_template_day_of_week_check CHECK (((day_of_week)::text = ANY ((ARRAY['MONDAY'::character varying, 'TUESDAY'::character varying, 'WEDNESDAY'::character varying, 'THURSDAY'::character varying, 'FRIDAY'::character varying, 'SATURDAY'::character varying, 'SUNDAY'::character varying])::text[])))
);


--
-- Name: provider_weekly_template_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.provider_weekly_template ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.provider_weekly_template_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: quiz_result; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.quiz_result (
    score integer NOT NULL,
    id bigint NOT NULL,
    interview_reminder_sent_at timestamp(6) without time zone,
    interview_scheduled_at timestamp(6) without time zone,
    submitted_at timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL,
    meeting_link character varying(255),
    status character varying(255) NOT NULL,
    CONSTRAINT quiz_result_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'ACCEPTED_QUIZ'::character varying, 'REJECTED'::character varying])::text[])))
);


--
-- Name: quiz_result_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.quiz_result ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quiz_result_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reschedule_request; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reschedule_request (
    original_duration double precision NOT NULL,
    proposed_duration double precision NOT NULL,
    booking_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    original_date timestamp(6) without time zone NOT NULL,
    proposed_date timestamp(6) without time zone NOT NULL,
    requested_by bigint NOT NULL,
    responded_at timestamp(6) without time zone,
    responded_by bigint,
    updated_at timestamp(6) without time zone,
    message character varying(500),
    response_message character varying(500),
    reason character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    CONSTRAINT reschedule_request_reason_check CHECK (((reason)::text = ANY ((ARRAY['SCHEDULING_CONFLICT'::character varying, 'DELAY'::character varying, 'CLIENT_REQUEST'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT reschedule_request_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'ACCEPTED'::character varying, 'REJECTED'::character varying, 'CANCELLED'::character varying])::text[])))
);


--
-- Name: reschedule_request_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reschedule_request ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reschedule_request_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reservation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reservation (
    date date NOT NULL,
    event_id bigint,
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


--
-- Name: reservation_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reservation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: review; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.review (
    rating integer NOT NULL,
    id bigint NOT NULL,
    product_id bigint,
    user_id bigint,
    comment character varying(255)
);


--
-- Name: review_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.review ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: seller_request; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.seller_request (
    date_demande timestamp(6) without time zone,
    date_validation timestamp(6) without time zone,
    id bigint NOT NULL,
    user_id bigint,
    validated_by bigint,
    numero_etudiant character varying(50) NOT NULL,
    nom character varying(100) NOT NULL,
    prenom character varying(100) NOT NULL,
    email character varying(320) NOT NULL,
    carte_etudiant_url character varying(500) NOT NULL,
    statut character varying(255),
    CONSTRAINT seller_request_statut_check CHECK (((statut)::text = ANY ((ARRAY['EN_ATTENTE'::character varying, 'APPROUVE'::character varying, 'REFUSE'::character varying])::text[])))
);


--
-- Name: seller_request_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.seller_request ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.seller_request_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: service; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.service (
    allow_project_participation boolean NOT NULL,
    price numeric(10,2),
    rating numeric(3,2),
    deleted_at timestamp(6) without time zone,
    id bigint NOT NULL,
    provider_id bigint,
    category character varying(255),
    description character varying(255),
    image_url character varying(255),
    location character varying(255),
    name character varying(255),
    pricing_type character varying(255),
    status character varying(255),
    CONSTRAINT service_category_check CHECK (((category)::text = ANY ((ARRAY['SRV'::character varying, 'CONSULTING'::character varying, 'DESIGN'::character varying, 'DEVELOPMENT'::character varying, 'MARKETING'::character varying, 'PHOTOGRAPHY'::character varying, 'WRITING'::character varying, 'TUTORING'::character varying, 'MAINTENANCE'::character varying, 'CLEANING'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT service_pricing_type_check CHECK (((pricing_type)::text = ANY ((ARRAY['HOURLY'::character varying, 'FIXED'::character varying, 'PACKAGED'::character varying])::text[]))),
    CONSTRAINT service_status_check CHECK (((status)::text = ANY ((ARRAY['AVAILABLE'::character varying, 'UNAVAILABLE'::character varying, 'BOOKED'::character varying])::text[])))
);


--
-- Name: service_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.service ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.service_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: service_mandate; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.service_mandate (
    max_bookings integer NOT NULL,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    provider_id bigint,
    service_id bigint,
    updated_at timestamp(6) without time zone
);


--
-- Name: service_mandate_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.service_mandate ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.service_mandate_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: service_packages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.service_packages (
    delivery_days integer,
    price numeric(10,2) NOT NULL,
    revisions integer,
    sort_order integer NOT NULL,
    id bigint NOT NULL,
    service_id bigint NOT NULL,
    name character varying(100) NOT NULL,
    description character varying(255),
    features text,
    tier character varying(255) NOT NULL,
    CONSTRAINT service_packages_tier_check CHECK (((tier)::text = ANY ((ARRAY['BASIC'::character varying, 'STANDARD'::character varying, 'PREMIUM'::character varying])::text[])))
);


--
-- Name: service_packages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.service_packages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.service_packages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: service_review; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.service_review (
    rating numeric(3,2),
    sentiment_confidence numeric(5,4),
    booking_id bigint,
    id bigint NOT NULL,
    user_id bigint,
    comment character varying(255),
    sentiment character varying(255)
);


--
-- Name: service_review_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.service_review ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.service_review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: service_tag; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.service_tag (
    id bigint NOT NULL,
    service_id bigint,
    tag character varying(255) NOT NULL
);


--
-- Name: service_tag_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.service_tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.service_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: slot_allocation_audit; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.slot_allocation_audit (
    final_score double precision NOT NULL,
    priority_markup_applied boolean NOT NULL,
    tie_breaker_weight double precision,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    project_id bigint,
    service_id bigint NOT NULL,
    slot_end timestamp(6) without time zone,
    slot_start timestamp(6) without time zone,
    mode character varying(40) NOT NULL,
    policy_profile character varying(40),
    reason_code character varying(80)
);


--
-- Name: slot_allocation_audit_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.slot_allocation_audit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.slot_allocation_audit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stall; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stall (
    number integer NOT NULL,
    event_id bigint,
    id bigint NOT NULL,
    user_id bigint,
    location character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    status character varying(50) DEFAULT 'ASSIGNED'::character varying NOT NULL
);


--
-- Name: stall_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.stall ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stall_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: store; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.store (
    active boolean,
    balance double precision,
    rating double precision,
    id bigint NOT NULL,
    owner_id bigint NOT NULL,
    logo_url character varying(2000),
    address character varying(255) NOT NULL,
    description character varying(255),
    name character varying(255) NOT NULL,
    phone character varying(255)
);


--
-- Name: store_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.store ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.store_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: store_users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.store_users (
    store_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: ticket; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ticket (
    discount_applied boolean NOT NULL,
    discount_rate double precision,
    final_price double precision,
    original_price double precision,
    price double precision NOT NULL,
    event_id bigint,
    id bigint NOT NULL,
    user_id bigint,
    discount_label character varying(255),
    payment_status character varying(50) DEFAULT 'PENDING'::character varying NOT NULL,
    stripe_payment_intent_id character varying(255),
    stripe_session_id character varying(255),
    type character varying(255) NOT NULL
);


--
-- Name: ticket_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ticket ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ticket_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: time_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.time_log (
    duration_minutes integer,
    booking_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    end_time timestamp(6) without time zone,
    id bigint NOT NULL,
    start_time timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL,
    description character varying(500)
);


--
-- Name: time_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.time_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.time_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_favorite; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_favorite (
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    service_id bigint,
    user_id bigint
);


--
-- Name: user_favorite_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_favorite ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_favorite_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vehicule; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vehicule (
    capacity double precision,
    id bigint NOT NULL,
    user_id bigint,
    registration_card_back_content_type character varying(255),
    registration_card_back_file_name character varying(255),
    registration_card_front_content_type character varying(255),
    registration_card_front_file_name character varying(255),
    registrationnumbers character varying(255),
    status character varying(255),
    type character varying(255),
    vehicle_photo_content_type character varying(255),
    vehicle_photo_file_name character varying(255),
    registration_card_back bytea,
    registration_card_front bytea,
    vehicle_photo bytea
);


--
-- Name: vehicule_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.vehicule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vehicule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wallet; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.wallet (
    balance double precision NOT NULL,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL
);


--
-- Name: wallet_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.wallet ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wallet_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wallet_transaction; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.wallet_transaction (
    amount double precision NOT NULL,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    reference_id bigint,
    wallet_id bigint NOT NULL,
    type character varying(30) NOT NULL,
    reference_type character varying(50),
    description character varying(500)
);


--
-- Name: wallet_transaction_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.wallet_transaction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wallet_transaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_user app_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_pkey PRIMARY KEY (id);


--
-- Name: application application_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application
    ADD CONSTRAINT application_pkey PRIMARY KEY (id);


--
-- Name: booking_attachment booking_attachment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.booking_attachment
    ADD CONSTRAINT booking_attachment_pkey PRIMARY KEY (id);


--
-- Name: booking_audit_log booking_audit_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.booking_audit_log
    ADD CONSTRAINT booking_audit_log_pkey PRIMARY KEY (id);


--
-- Name: booking_message booking_message_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.booking_message
    ADD CONSTRAINT booking_message_pkey PRIMARY KEY (id);


--
-- Name: booking booking_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.booking
    ADD CONSTRAINT booking_pkey PRIMARY KEY (id);


--
-- Name: category category_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_pkey PRIMARY KEY (id);


--
-- Name: collaboration collaboration_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.collaboration
    ADD CONSTRAINT collaboration_pkey PRIMARY KEY (id);


--
-- Name: courier courier_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courier
    ADD CONSTRAINT courier_pkey PRIMARY KEY (id);


--
-- Name: courier courier_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courier
    ADD CONSTRAINT courier_user_id_key UNIQUE (user_id);


--
-- Name: deliverable_attachment deliverable_attachment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deliverable_attachment
    ADD CONSTRAINT deliverable_attachment_pkey PRIMARY KEY (id);


--
-- Name: deliverable deliverable_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deliverable
    ADD CONSTRAINT deliverable_pkey PRIMARY KEY (id);


--
-- Name: deliverable_review deliverable_review_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deliverable_review
    ADD CONSTRAINT deliverable_review_pkey PRIMARY KEY (id);


--
-- Name: deliverable_version_attachment deliverable_version_attachment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deliverable_version_attachment
    ADD CONSTRAINT deliverable_version_attachment_pkey PRIMARY KEY (id);


--
-- Name: deliverable_version deliverable_version_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deliverable_version
    ADD CONSTRAINT deliverable_version_pkey PRIMARY KEY (id);


--
-- Name: delivery_address_details delivery_address_details_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.delivery_address_details
    ADD CONSTRAINT delivery_address_details_pkey PRIMARY KEY (id);


--
-- Name: delivery delivery_order_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.delivery
    ADD CONSTRAINT delivery_order_id_key UNIQUE (order_id);


--
-- Name: delivery delivery_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.delivery
    ADD CONSTRAINT delivery_pkey PRIMARY KEY (id);


--
-- Name: delivery delivery_qr_token_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.delivery
    ADD CONSTRAINT delivery_qr_token_key UNIQUE (qr_token);


--
-- Name: delivery delivery_tracking_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.delivery
    ADD CONSTRAINT delivery_tracking_id_key UNIQUE (tracking_id);


--
-- Name: dispute_mediation dispute_mediation_booking_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dispute_mediation
    ADD CONSTRAINT dispute_mediation_booking_id_key UNIQUE (booking_id);


--
-- Name: dispute_mediation dispute_mediation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dispute_mediation
    ADD CONSTRAINT dispute_mediation_pkey PRIMARY KEY (id);


--
-- Name: equipment equipment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.equipment
    ADD CONSTRAINT equipment_pkey PRIMARY KEY (id);


--
-- Name: equipment_reservation equipment_reservation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.equipment_reservation
    ADD CONSTRAINT equipment_reservation_pkey PRIMARY KEY (id);


--
-- Name: escrow_hold escrow_hold_booking_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.escrow_hold
    ADD CONSTRAINT escrow_hold_booking_id_key UNIQUE (booking_id);


--
-- Name: escrow_hold escrow_hold_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.escrow_hold
    ADD CONSTRAINT escrow_hold_pkey PRIMARY KEY (id);


--
-- Name: event event_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event
    ADD CONSTRAINT event_pkey PRIMARY KEY (id);


--
-- Name: interview interview_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interview
    ADD CONSTRAINT interview_pkey PRIMARY KEY (id);


--
-- Name: job_offer job_offer_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.job_offer
    ADD CONSTRAINT job_offer_pkey PRIMARY KEY (id);


--
-- Name: map_tracking map_tracking_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.map_tracking
    ADD CONSTRAINT map_tracking_pkey PRIMARY KEY (id);


--
-- Name: messages messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_pkey PRIMARY KEY (id);


--
-- Name: milestone_bookings milestone_bookings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.milestone_bookings
    ADD CONSTRAINT milestone_bookings_pkey PRIMARY KEY (booking_id, milestone_id);


--
-- Name: milestone_services milestone_services_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.milestone_services
    ADD CONSTRAINT milestone_services_pkey PRIMARY KEY (milestone_id, service_id);


--
-- Name: notification notification_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT notification_pkey PRIMARY KEY (id);


--
-- Name: order_lines order_lines_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_lines
    ADD CONSTRAINT order_lines_pkey PRIMARY KEY (id);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- Name: partner_company partner_company_contact_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partner_company
    ADD CONSTRAINT partner_company_contact_email_key UNIQUE (contact_email);


--
-- Name: partner_company partner_company_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partner_company
    ADD CONSTRAINT partner_company_pkey PRIMARY KEY (id);


--
-- Name: partner partner_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partner
    ADD CONSTRAINT partner_pkey PRIMARY KEY (id);


--
-- Name: partner_projects partner_projects_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partner_projects
    ADD CONSTRAINT partner_projects_pkey PRIMARY KEY (partner_id, project_id);


--
-- Name: partner_services partner_services_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partner_services
    ADD CONSTRAINT partner_services_pkey PRIMARY KEY (partner_id, service_id);


--
-- Name: partnership_notification partnership_notification_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partnership_notification
    ADD CONSTRAINT partnership_notification_pkey PRIMARY KEY (id);


--
-- Name: password_reset_code password_reset_code_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_code
    ADD CONSTRAINT password_reset_code_pkey PRIMARY KEY (id);


--
-- Name: product product_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_pkey PRIMARY KEY (id);


--
-- Name: profil profil_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profil
    ADD CONSTRAINT profil_pkey PRIMARY KEY (id);


--
-- Name: profil profil_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profil
    ADD CONSTRAINT profil_user_id_key UNIQUE (user_id);


--
-- Name: project_dependency project_dependency_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_dependency
    ADD CONSTRAINT project_dependency_pkey PRIMARY KEY (id);


--
-- Name: project_milestone project_milestone_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_milestone
    ADD CONSTRAINT project_milestone_pkey PRIMARY KEY (id);


--
-- Name: project project_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project
    ADD CONSTRAINT project_pkey PRIMARY KEY (id);


--
-- Name: project_services project_services_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_services
    ADD CONSTRAINT project_services_pkey PRIMARY KEY (project_id, service_id);


--
-- Name: project_users project_users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_users
    ADD CONSTRAINT project_users_pkey PRIMARY KEY (project_id, user_id);


--
-- Name: provider_exception provider_exception_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_exception
    ADD CONSTRAINT provider_exception_pkey PRIMARY KEY (id);


--
-- Name: provider_mandate provider_mandate_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_mandate
    ADD CONSTRAINT provider_mandate_pkey PRIMARY KEY (id);


--
-- Name: provider_weekly_template provider_weekly_template_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_weekly_template
    ADD CONSTRAINT provider_weekly_template_pkey PRIMARY KEY (id);


--
-- Name: quiz_result quiz_result_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quiz_result
    ADD CONSTRAINT quiz_result_pkey PRIMARY KEY (id);


--
-- Name: reschedule_request reschedule_request_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reschedule_request
    ADD CONSTRAINT reschedule_request_pkey PRIMARY KEY (id);


--
-- Name: reservation reservation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservation
    ADD CONSTRAINT reservation_pkey PRIMARY KEY (id);


--
-- Name: review review_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT review_pkey PRIMARY KEY (id);


--
-- Name: seller_request seller_request_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seller_request
    ADD CONSTRAINT seller_request_pkey PRIMARY KEY (id);


--
-- Name: service_mandate service_mandate_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.service_mandate
    ADD CONSTRAINT service_mandate_pkey PRIMARY KEY (id);


--
-- Name: service_packages service_packages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.service_packages
    ADD CONSTRAINT service_packages_pkey PRIMARY KEY (id);


--
-- Name: service_packages service_packages_service_id_tier_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.service_packages
    ADD CONSTRAINT service_packages_service_id_tier_key UNIQUE (service_id, tier);


--
-- Name: service service_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.service
    ADD CONSTRAINT service_pkey PRIMARY KEY (id);


--
-- Name: service_review service_review_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.service_review
    ADD CONSTRAINT service_review_pkey PRIMARY KEY (id);


--
-- Name: service_tag service_tag_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.service_tag
    ADD CONSTRAINT service_tag_pkey PRIMARY KEY (id);


--
-- Name: slot_allocation_audit slot_allocation_audit_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.slot_allocation_audit
    ADD CONSTRAINT slot_allocation_audit_pkey PRIMARY KEY (id);


--
-- Name: stall stall_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stall
    ADD CONSTRAINT stall_pkey PRIMARY KEY (id);


--
-- Name: store store_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.store
    ADD CONSTRAINT store_pkey PRIMARY KEY (id);


--
-- Name: ticket ticket_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ticket
    ADD CONSTRAINT ticket_pkey PRIMARY KEY (id);


--
-- Name: time_log time_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.time_log
    ADD CONSTRAINT time_log_pkey PRIMARY KEY (id);


--
-- Name: reschedule_request uk_active_reschedule; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reschedule_request
    ADD CONSTRAINT uk_active_reschedule UNIQUE (booking_id, status);


--
-- Name: project_dependency uk_project_dependency_pair; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_dependency
    ADD CONSTRAINT uk_project_dependency_pair UNIQUE (project_id, predecessor_milestone_id, successor_milestone_id);


--
-- Name: user_favorite user_favorite_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_favorite
    ADD CONSTRAINT user_favorite_pkey PRIMARY KEY (id);


--
-- Name: vehicule vehicule_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicule
    ADD CONSTRAINT vehicule_pkey PRIMARY KEY (id);


--
-- Name: wallet wallet_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wallet
    ADD CONSTRAINT wallet_pkey PRIMARY KEY (id);


--
-- Name: wallet_transaction wallet_transaction_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wallet_transaction
    ADD CONSTRAINT wallet_transaction_pkey PRIMARY KEY (id);


--
-- Name: wallet wallet_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wallet
    ADD CONSTRAINT wallet_user_id_key UNIQUE (user_id);


--
-- Name: idx_notif_recipient_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notif_recipient_created ON public.notification USING btree (recipient_id, created_at);


--
-- Name: idx_notif_recipient_read; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notif_recipient_read ON public.notification USING btree (recipient_id, is_read);


--
-- Name: profil_languages fk186n3ybe0p8oitb5os40itup3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profil_languages
    ADD CONSTRAINT fk186n3ybe0p8oitb5os40itup3 FOREIGN KEY (profil_id) REFERENCES public.profil(id);


--
-- Name: delivery fk18gx1bkljebrip0mpqy759o7g; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.delivery
    ADD CONSTRAINT fk18gx1bkljebrip0mpqy759o7g FOREIGN KEY (tracking_id) REFERENCES public.map_tracking(id);


--
-- Name: product fk1mtsbur82frn64de7balymq9s; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT fk1mtsbur82frn64de7balymq9s FOREIGN KEY (category_id) REFERENCES public.category(id);


--
-- Name: stall fk1p3h6rdr8fe74v3nwncjrh032; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stall
    ADD CONSTRAINT fk1p3h6rdr8fe74v3nwncjrh032 FOREIGN KEY (event_id) REFERENCES public.event(id);


--
-- Name: order_lines fk1smc0s578t2oih21yn9hw6usr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_lines
    ADD CONSTRAINT fk1smc0s578t2oih21yn9hw6usr FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: delivery fk1vauj6m7bc5jf1cl6ntryhvqr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.delivery
    ADD CONSTRAINT fk1vauj6m7bc5jf1cl6ntryhvqr FOREIGN KEY (vehicule_id) REFERENCES public.vehicule(id);


--
-- Name: time_log fk227y9pywbap6duwbkuxag0vqw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.time_log
    ADD CONSTRAINT fk227y9pywbap6duwbkuxag0vqw FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: courier fk22mspbdrjl8r3iq99jfvpo3wy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courier
    ADD CONSTRAINT fk22mspbdrjl8r3iq99jfvpo3wy FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: delivery fk25eaurt0ya6iclof263nm7fxj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.delivery
    ADD CONSTRAINT fk25eaurt0ya6iclof263nm7fxj FOREIGN KEY (address_details_id) REFERENCES public.delivery_address_details(id);


--
-- Name: project_dependency fk2h7xxv0vjduajoecwjasa20ob; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_dependency
    ADD CONSTRAINT fk2h7xxv0vjduajoecwjasa20ob FOREIGN KEY (project_id) REFERENCES public.project(id);


--
-- Name: seller_request fk2jxldrewyh6bf4thjby3qyqbs; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seller_request
    ADD CONSTRAINT fk2jxldrewyh6bf4thjby3qyqbs FOREIGN KEY (validated_by) REFERENCES public.app_user(id);


--
-- Name: reschedule_request fk2y0fwkx04yrq4xe9a1hjdsa4h; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reschedule_request
    ADD CONSTRAINT fk2y0fwkx04yrq4xe9a1hjdsa4h FOREIGN KEY (booking_id) REFERENCES public.booking(id);


--
-- Name: user_favorite fk34q3k4is454925e4itp82ah9q; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_favorite
    ADD CONSTRAINT fk34q3k4is454925e4itp82ah9q FOREIGN KEY (service_id) REFERENCES public.service(id);


--
-- Name: application_languages fk3dxocmmywjh78hn40ko24tplt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_languages
    ADD CONSTRAINT fk3dxocmmywjh78hn40ko24tplt FOREIGN KEY (application_id) REFERENCES public.application(id);


--
-- Name: application_skills fk3vwaof5845bv9lqwsx2h37qtj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_skills
    ADD CONSTRAINT fk3vwaof5845bv9lqwsx2h37qtj FOREIGN KEY (application_id) REFERENCES public.application(id);


--
-- Name: product_users fk4sncgsei26o0iujofcxommfwr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_users
    ADD CONSTRAINT fk4sncgsei26o0iujofcxommfwr FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: project fk5halg556cgn6wu7vs8dbnb2ih; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project
    ADD CONSTRAINT fk5halg556cgn6wu7vs8dbnb2ih FOREIGN KEY (creator_id) REFERENCES public.app_user(id);


--
-- Name: collaboration fk5ufivd89hvmxrf0ngrg9aonvo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.collaboration
    ADD CONSTRAINT fk5ufivd89hvmxrf0ngrg9aonvo FOREIGN KEY (event_id) REFERENCES public.event(id);


--
-- Name: deliverable_review fk66ppievshekxcnf4g0kc7ghao; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deliverable_review
    ADD CONSTRAINT fk66ppievshekxcnf4g0kc7ghao FOREIGN KEY (deliverable_id) REFERENCES public.deliverable(id);


--
-- Name: wallet_transaction fk6cnvafp3a0xhbs0eh9w26sett; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wallet_transaction
    ADD CONSTRAINT fk6cnvafp3a0xhbs0eh9w26sett FOREIGN KEY (wallet_id) REFERENCES public.wallet(id);


--
-- Name: stall fk6riepm5i8py133b7jn08607hb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stall
    ADD CONSTRAINT fk6riepm5i8py133b7jn08607hb FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: event fk6s8tfh087wqpb5ij1v9ndk4t2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event
    ADD CONSTRAINT fk6s8tfh087wqpb5ij1v9ndk4t2 FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: reservation fk7frrxg8uwj7ekfxebjrumyjfo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservation
    ADD CONSTRAINT fk7frrxg8uwj7ekfxebjrumyjfo FOREIGN KEY (event_id) REFERENCES public.event(id);


--
-- Name: equipment_reservation fk7lw50luax14vmohkktlbmmlvv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.equipment_reservation
    ADD CONSTRAINT fk7lw50luax14vmohkktlbmmlvv FOREIGN KEY (equipment_id) REFERENCES public.equipment(id);


--
-- Name: booking_attachment fk7n3hmddap4hcdmonkimmtffes; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.booking_attachment
    ADD CONSTRAINT fk7n3hmddap4hcdmonkimmtffes FOREIGN KEY (uploaded_by) REFERENCES public.app_user(id);


--
-- Name: deliverable fk83lp1r64fhko81t0d893qiriy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deliverable
    ADD CONSTRAINT fk83lp1r64fhko81t0d893qiriy FOREIGN KEY (booking_id) REFERENCES public.booking(id);


--
-- Name: booking_message fk8bss4hm8mq8ykhuju6fvmgheo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.booking_message
    ADD CONSTRAINT fk8bss4hm8mq8ykhuju6fvmgheo FOREIGN KEY (booking_id) REFERENCES public.booking(id);


--
-- Name: milestone_bookings fk8kdejdnxd79nmdl1d84jwvg9v; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.milestone_bookings
    ADD CONSTRAINT fk8kdejdnxd79nmdl1d84jwvg9v FOREIGN KEY (booking_id) REFERENCES public.booking(id);


--
-- Name: store fk8mh90bbxgoxx2pjcfd8q6j9aw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.store
    ADD CONSTRAINT fk8mh90bbxgoxx2pjcfd8q6j9aw FOREIGN KEY (owner_id) REFERENCES public.app_user(id);


--
-- Name: milestone_services fk8qdfj8r3t3ghjl024a1gvl3af; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.milestone_services
    ADD CONSTRAINT fk8qdfj8r3t3ghjl024a1gvl3af FOREIGN KEY (service_id) REFERENCES public.service(id);


--
-- Name: service_packages fk8t0tgmtworxliam4v2ybagqf3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.service_packages
    ADD CONSTRAINT fk8t0tgmtworxliam4v2ybagqf3 FOREIGN KEY (service_id) REFERENCES public.service(id);


--
-- Name: wallet fk8xcge928o78vtbh64bddusygy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wallet
    ADD CONSTRAINT fk8xcge928o78vtbh64bddusygy FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: project_services fk996aa1xcqkh8j1bq4ml4effpi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_services
    ADD CONSTRAINT fk996aa1xcqkh8j1bq4ml4effpi FOREIGN KEY (service_id) REFERENCES public.service(id);


--
-- Name: project_users fk9at0ei37rls7vd2m6sh92668h; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_users
    ADD CONSTRAINT fk9at0ei37rls7vd2m6sh92668h FOREIGN KEY (project_id) REFERENCES public.project(id);


--
-- Name: booking fk9o6mkk9jyl2g3kwqluefv9kym; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.booking
    ADD CONSTRAINT fk9o6mkk9jyl2g3kwqluefv9kym FOREIGN KEY (partner_id) REFERENCES public.partner(id);


--
-- Name: seller_request fka2w32x17ur7ao6w94ws8l9cs7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seller_request
    ADD CONSTRAINT fka2w32x17ur7ao6w94ws8l9cs7 FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: deliverable fkannhidbkl97276nfetcecbs6k; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deliverable
    ADD CONSTRAINT fkannhidbkl97276nfetcecbs6k FOREIGN KEY (provider_id) REFERENCES public.app_user(id);


--
-- Name: booking_attachment fkaoubx5btes0csahj2n1b6q12o; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.booking_attachment
    ADD CONSTRAINT fkaoubx5btes0csahj2n1b6q12o FOREIGN KEY (booking_id) REFERENCES public.booking(id);


--
-- Name: service fkb34tb1ah653eb3i49viqoihr7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.service
    ADD CONSTRAINT fkb34tb1ah653eb3i49viqoihr7 FOREIGN KEY (provider_id) REFERENCES public.app_user(id);


--
-- Name: provider_weekly_template fkb7j6gckc5aa5xwo3v0y10xfbu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_weekly_template
    ADD CONSTRAINT fkb7j6gckc5aa5xwo3v0y10xfbu FOREIGN KEY (provider_id) REFERENCES public.app_user(id);


--
-- Name: partner_services fkb9yhi0tx9kqkq3usry124ghcs; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partner_services
    ADD CONSTRAINT fkb9yhi0tx9kqkq3usry124ghcs FOREIGN KEY (partner_id) REFERENCES public.partner(id);


--
-- Name: vehicule fkbochos2829gh2jwxe9vqft9ic; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicule
    ADD CONSTRAINT fkbochos2829gh2jwxe9vqft9ic FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: review fkc7y0l3wac4n2ewm6a2uecd54c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT fkc7y0l3wac4n2ewm6a2uecd54c FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: booking fkcebnlefwi9r13txu8btclnmsu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.booking
    ADD CONSTRAINT fkcebnlefwi9r13txu8btclnmsu FOREIGN KEY (service_id) REFERENCES public.service(id);


--
-- Name: deliverable_version fkcq068trcnmog1okowp3e2dfdt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deliverable_version
    ADD CONSTRAINT fkcq068trcnmog1okowp3e2dfdt FOREIGN KEY (deliverable_id) REFERENCES public.deliverable(id);


--
-- Name: equipment_reservation fkct84wwwf8swnbfbtr904adnqa; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.equipment_reservation
    ADD CONSTRAINT fkct84wwwf8swnbfbtr904adnqa FOREIGN KEY (reservation_id) REFERENCES public.reservation(id);


--
-- Name: escrow_hold fkcw59vn885j4dmitrk3djal3om; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.escrow_hold
    ADD CONSTRAINT fkcw59vn885j4dmitrk3djal3om FOREIGN KEY (booking_id) REFERENCES public.booking(id);


--
-- Name: dispute_mediation fkdoy31sholpa6sk5nkviefmjdw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dispute_mediation
    ADD CONSTRAINT fkdoy31sholpa6sk5nkviefmjdw FOREIGN KEY (booking_id) REFERENCES public.booking(id);


--
-- Name: project_dependency fkdsca6c3u6cnq2q3lu6d2obs0h; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_dependency
    ADD CONSTRAINT fkdsca6c3u6cnq2q3lu6d2obs0h FOREIGN KEY (predecessor_milestone_id) REFERENCES public.project_milestone(id);


--
-- Name: interview fkdyrt85lva791fmh1qnhf0ee0f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interview
    ADD CONSTRAINT fkdyrt85lva791fmh1qnhf0ee0f FOREIGN KEY (application_id) REFERENCES public.application(id);


--
-- Name: ticket fkemcfkpg53qt9pdg5y6rtq35wf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ticket
    ADD CONSTRAINT fkemcfkpg53qt9pdg5y6rtq35wf FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: equipment fkfil1tovuurf1j1rfgr40csa2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.equipment
    ADD CONSTRAINT fkfil1tovuurf1j1rfgr40csa2 FOREIGN KEY (event_id) REFERENCES public.event(id);


--
-- Name: provider_weekly_template fkfthpbhvo6smbawok6qbdtpyjm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_weekly_template
    ADD CONSTRAINT fkfthpbhvo6smbawok6qbdtpyjm FOREIGN KEY (service_id) REFERENCES public.service(id);


--
-- Name: ticket fkfytuhjopeamxbt1cpudy92x5n; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ticket
    ADD CONSTRAINT fkfytuhjopeamxbt1cpudy92x5n FOREIGN KEY (event_id) REFERENCES public.event(id);


--
-- Name: time_log fkgtve2b9u65equ2ds0w5poy7m; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.time_log
    ADD CONSTRAINT fkgtve2b9u65equ2ds0w5poy7m FOREIGN KEY (booking_id) REFERENCES public.booking(id);


--
-- Name: milestone_bookings fkh1juoyh154inq1yqkplppox4q; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.milestone_bookings
    ADD CONSTRAINT fkh1juoyh154inq1yqkplppox4q FOREIGN KEY (milestone_id) REFERENCES public.project_milestone(id);


--
-- Name: partner_services fkhaslrn4ie3gcge5fvmhl4w7no; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partner_services
    ADD CONSTRAINT fkhaslrn4ie3gcge5fvmhl4w7no FOREIGN KEY (service_id) REFERENCES public.service(id);


--
-- Name: service_review fki0tblpefthw337ey4mk6kw949; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.service_review
    ADD CONSTRAINT fki0tblpefthw337ey4mk6kw949 FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: job_offer fkid3cyhhfg1587g6vbdvu62qhx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.job_offer
    ADD CONSTRAINT fkid3cyhhfg1587g6vbdvu62qhx FOREIGN KEY (company_id) REFERENCES public.partner_company(id);


--
-- Name: application fkiyewk3kxwqpqybhenxw2qqn6s; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application
    ADD CONSTRAINT fkiyewk3kxwqpqybhenxw2qqn6s FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: review fkiyof1sindb9qiqr9o8npj8klt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT fkiyof1sindb9qiqr9o8npj8klt FOREIGN KEY (product_id) REFERENCES public.product(id);


--
-- Name: quiz_result fkjf64g3yckrjaxdbf65dru3arm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quiz_result
    ADD CONSTRAINT fkjf64g3yckrjaxdbf65dru3arm FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: provider_mandate fkjj0wav9c5mqxqo9awsq8danp7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_mandate
    ADD CONSTRAINT fkjj0wav9c5mqxqo9awsq8danp7 FOREIGN KEY (provider_id) REFERENCES public.app_user(id);


--
-- Name: store_users fkjl53q6xcvncg1l0hk77rf0j54; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.store_users
    ADD CONSTRAINT fkjl53q6xcvncg1l0hk77rf0j54 FOREIGN KEY (store_id) REFERENCES public.store(id);


--
-- Name: product fkjlfidudl1gwqem0flrlomvlcl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT fkjlfidudl1gwqem0flrlomvlcl FOREIGN KEY (store_id) REFERENCES public.store(id);


--
-- Name: application fkjp7yaago8i6ndvghp4ww8m6f1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application
    ADD CONSTRAINT fkjp7yaago8i6ndvghp4ww8m6f1 FOREIGN KEY (job_offer_id) REFERENCES public.job_offer(id);


--
-- Name: service_mandate fkjwnns60stvobhk6e0uv0cudr8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.service_mandate
    ADD CONSTRAINT fkjwnns60stvobhk6e0uv0cudr8 FOREIGN KEY (service_id) REFERENCES public.service(id);


--
-- Name: reschedule_request fkjxlam01g4cfd6wddaupmu2oq2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reschedule_request
    ADD CONSTRAINT fkjxlam01g4cfd6wddaupmu2oq2 FOREIGN KEY (responded_by) REFERENCES public.app_user(id);


--
-- Name: product_users fkk994x31yrhc9jo8gqa5i0koih; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_users
    ADD CONSTRAINT fkk994x31yrhc9jo8gqa5i0koih FOREIGN KEY (product_id) REFERENCES public.product(id);


--
-- Name: partner_projects fkkc8bgbq986ks951d0x142j2n5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partner_projects
    ADD CONSTRAINT fkkc8bgbq986ks951d0x142j2n5 FOREIGN KEY (partner_id) REFERENCES public.partner(id);


--
-- Name: project_services fkkcqv6t9sq0sipjhyg7bvjv4jy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_services
    ADD CONSTRAINT fkkcqv6t9sq0sipjhyg7bvjv4jy FOREIGN KEY (project_id) REFERENCES public.project(id);


--
-- Name: profil fkkqhfdv5u7ur8aqhblu4cwjfgg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profil
    ADD CONSTRAINT fkkqhfdv5u7ur8aqhblu4cwjfgg FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: deliverable_review fkkrc4l972oxtilf6jxgqvh20qv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deliverable_review
    ADD CONSTRAINT fkkrc4l972oxtilf6jxgqvh20qv FOREIGN KEY (reviewer_id) REFERENCES public.app_user(id);


--
-- Name: project_dependency fkksu6shn7voc691d42u85nf5m7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_dependency
    ADD CONSTRAINT fkksu6shn7voc691d42u85nf5m7 FOREIGN KEY (successor_milestone_id) REFERENCES public.project_milestone(id);


--
-- Name: deliverable_attachment fkl1btk8f2jhsqjm6smxufylun5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deliverable_attachment
    ADD CONSTRAINT fkl1btk8f2jhsqjm6smxufylun5 FOREIGN KEY (deliverable_id) REFERENCES public.deliverable(id);


--
-- Name: service_mandate fkl1q98dtwopfdx4j8g6cy1f3u4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.service_mandate
    ADD CONSTRAINT fkl1q98dtwopfdx4j8g6cy1f3u4 FOREIGN KEY (provider_id) REFERENCES public.app_user(id);


--
-- Name: store_users fkmh2ty44fhtio4ckd2vuhxd481; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.store_users
    ADD CONSTRAINT fkmh2ty44fhtio4ckd2vuhxd481 FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: booking fkn7phgawjwo673xgim9d2cvfe1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.booking
    ADD CONSTRAINT fkn7phgawjwo673xgim9d2cvfe1 FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: milestone_services fknsnu3kp6t8inm8kysq02veh5h; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.milestone_services
    ADD CONSTRAINT fknsnu3kp6t8inm8kysq02veh5h FOREIGN KEY (milestone_id) REFERENCES public.project_milestone(id);


--
-- Name: order_lines fko53tpdwnm0fxnexfslqpk9dq4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_lines
    ADD CONSTRAINT fko53tpdwnm0fxnexfslqpk9dq4 FOREIGN KEY (product_id) REFERENCES public.product(id);


--
-- Name: booking fko8o0scoppv66hnb0p0sv0f8na; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.booking
    ADD CONSTRAINT fko8o0scoppv66hnb0p0sv0f8na FOREIGN KEY (provider_id) REFERENCES public.app_user(id);


--
-- Name: project_milestone fkoc8e2oiu6y0gdy1xfwvxexcym; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_milestone
    ADD CONSTRAINT fkoc8e2oiu6y0gdy1xfwvxexcym FOREIGN KEY (project_id) REFERENCES public.project(id);


--
-- Name: provider_exception fkof6cota0lngeohvwl6vg9sysm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_exception
    ADD CONSTRAINT fkof6cota0lngeohvwl6vg9sysm FOREIGN KEY (provider_id) REFERENCES public.app_user(id);


--
-- Name: booking fkoff92mxy06fmm62ujbtu156qq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.booking
    ADD CONSTRAINT fkoff92mxy06fmm62ujbtu156qq FOREIGN KEY (project_id) REFERENCES public.project(id);


--
-- Name: booking_message fkogn04b8dkqykgl56qjx6rc4wi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.booking_message
    ADD CONSTRAINT fkogn04b8dkqykgl56qjx6rc4wi FOREIGN KEY (sender_id) REFERENCES public.app_user(id);


--
-- Name: orders fkosotb7rvgk4myda45ki0cf9j; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fkosotb7rvgk4myda45ki0cf9j FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: reschedule_request fkprk4javgmaok3opy62bcy6hvk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reschedule_request
    ADD CONSTRAINT fkprk4javgmaok3opy62bcy6hvk FOREIGN KEY (requested_by) REFERENCES public.app_user(id);


--
-- Name: service_review fkpyr6iecd1nba3hk9i2lvvno73; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.service_review
    ADD CONSTRAINT fkpyr6iecd1nba3hk9i2lvvno73 FOREIGN KEY (booking_id) REFERENCES public.booking(id);


--
-- Name: category fkqdaotwkf5g9vmdox82ttt50i5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT fkqdaotwkf5g9vmdox82ttt50i5 FOREIGN KEY (store_id) REFERENCES public.store(id);


--
-- Name: partner_projects fkr97u91frmx5xomaoo6qssasl1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partner_projects
    ADD CONSTRAINT fkr97u91frmx5xomaoo6qssasl1 FOREIGN KEY (project_id) REFERENCES public.project(id);


--
-- Name: service_tag fkrsacpd8hp3ldg9v2naql73p6p; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.service_tag
    ADD CONSTRAINT fkrsacpd8hp3ldg9v2naql73p6p FOREIGN KEY (service_id) REFERENCES public.service(id);


--
-- Name: user_favorite fkskxuha6p1cyvw36uworh62q5u; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_favorite
    ADD CONSTRAINT fkskxuha6p1cyvw36uworh62q5u FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: equipment_reservation fksrv9cy1tc4vurcnw6pocu1l2j; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.equipment_reservation
    ADD CONSTRAINT fksrv9cy1tc4vurcnw6pocu1l2j FOREIGN KEY (stall_id) REFERENCES public.stall(id);


--
-- Name: profil_skills fksvc58m8qbbffk3mmadstht4bs; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profil_skills
    ADD CONSTRAINT fksvc58m8qbbffk3mmadstht4bs FOREIGN KEY (profil_id) REFERENCES public.profil(id);


--
-- Name: escrow_hold fkt1nlfi1bei52tf3drrskjd5br; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.escrow_hold
    ADD CONSTRAINT fkt1nlfi1bei52tf3drrskjd5br FOREIGN KEY (wallet_id) REFERENCES public.wallet(id);


--
-- Name: project_users fkt239opabjfy9t23vxurulhsjq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_users
    ADD CONSTRAINT fkt239opabjfy9t23vxurulhsjq FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: app_user fkt6pg6o1cuu5uec597145ot597; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT fkt6pg6o1cuu5uec597145ot597 FOREIGN KEY (partner_id) REFERENCES public.partner(id);


--
-- Name: deliverable_version_attachment fktcp2ks6t3k0tonw7wjc4taf2f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deliverable_version_attachment
    ADD CONSTRAINT fktcp2ks6t3k0tonw7wjc4taf2f FOREIGN KEY (deliverable_version_id) REFERENCES public.deliverable_version(id);


--
-- Name: delivery fku4e8rjwmg09vmas3ccjwglso; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.delivery
    ADD CONSTRAINT fku4e8rjwmg09vmas3ccjwglso FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- PostgreSQL database dump complete
--

\unrestrict HNdliL8SFWn7G4odm2bWH0GUj2Sp2kE27Ork59x1qc1Kb5lROh46JtaVRzViV60

