global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'esprit-gateway'
    metrics_path: /actuator/prometheus
    scrape_interval: 10s
    static_configs:
      - targets: ['backend:8088']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'esprit-gateway'

  - job_name: 'esprit-auth'
    metrics_path: /actuator/prometheus
    scrape_interval: 10s
    static_configs:
      - targets: ['auth:8081']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'esprit-auth'

  - job_name: 'esprit-marketplace'
    metrics_path: /actuator/prometheus
    scrape_interval: 10s
    static_configs:
      - targets: ['marketplace:8082']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'esprit-marketplace'

  - job_name: 'esprit-srv'
    metrics_path: /actuator/prometheus
    scrape_interval: 10s
    static_configs:
      - targets: ['srv:8083']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'esprit-srv'

  - job_name: 'esprit-eventplanning'
    metrics_path: /actuator/prometheus
    scrape_interval: 10s
    static_configs:
      - targets: ['eventplanning:8084']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'esprit-eventplanning'

  - job_name: 'esprit-partnership'
    metrics_path: /actuator/prometheus
    scrape_interval: 10s
    static_configs:
      - targets: ['partnership:8085']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'esprit-partnership'

  - job_name: 'eureka-server'
    metrics_path: /actuator/prometheus
    scrape_interval: 10s
    static_configs:
      - targets: ['eureka:8761']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'eureka-server'
