FROM node:20-alpine
WORKDIR /app

COPY package*.json tsconfig*.json angular.json tailwind.config.ts postcss.config.json ./

RUN npm install --silent

COPY src ./src
COPY public ./public

EXPOSE 4200

CMD ["npx", "ng", "serve", "--host", "0.0.0.0", "--port", "4200", "--poll", "500"]
