-- Partnership2: Add advanced application tracking columns
ALTER TABLE application ADD COLUMN IF NOT EXISTS motivation TEXT;
ALTER TABLE application ADD COLUMN IF NOT EXISTS experience_level VARCHAR(255);
ALTER TABLE application ADD COLUMN IF NOT EXISTS field_of_study VARCHAR(255);
ALTER TABLE application ADD COLUMN IF NOT EXISTS years_of_experience VARCHAR(255);
ALTER TABLE application ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE application ADD COLUMN IF NOT EXISTS last_candidate_action_at TIMESTAMP;
ALTER TABLE application ADD COLUMN IF NOT EXISTS activity_status VARCHAR(255) DEFAULT 'ACTIVE';
ALTER TABLE application ADD COLUMN IF NOT EXISTS is_flagged BOOLEAN DEFAULT FALSE;

-- Partnership2: Add interview tracking columns
ALTER TABLE interview ADD COLUMN IF NOT EXISTS location VARCHAR(255);
ALTER TABLE interview ADD COLUMN IF NOT EXISTS status VARCHAR(255) DEFAULT 'SCHEDULED';
ALTER TABLE interview ADD COLUMN IF NOT EXISTS result_notes TEXT;
ALTER TABLE interview ALTER COLUMN interview_date TYPE TIMESTAMP;

-- Partnership2: Add job offer tracking columns
ALTER TABLE job_offer ADD COLUMN IF NOT EXISTS location VARCHAR(255);
ALTER TABLE job_offer ADD COLUMN IF NOT EXISTS experience_level VARCHAR(255);
ALTER TABLE job_offer ADD COLUMN IF NOT EXISTS required_skills TEXT;

-- Partnership2: Application skill/language collection tables
CREATE TABLE IF NOT EXISTS application_skills (
    application_id BIGINT NOT NULL REFERENCES application(id) ON DELETE CASCADE,
    skills VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS application_languages (
    application_id BIGINT NOT NULL REFERENCES application(id) ON DELETE CASCADE,
    languages VARCHAR(255) NOT NULL
);

-- Partnership2: Partnership notifications table
CREATE TABLE IF NOT EXISTS partnership_notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message TEXT NOT NULL,
    type VARCHAR(255) NOT NULL,
    user_id BIGINT NOT NULL,
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP
);
