-- Partnership2: Profil table and element collections
CREATE TABLE IF NOT EXISTS profil (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT UNIQUE REFERENCES app_user(id),
    experience_level VARCHAR(255),
    field_of_study VARCHAR(255),
    years_of_experience VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS profil_skills (
    profil_id BIGINT NOT NULL REFERENCES profil(id) ON DELETE CASCADE,
    skills VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS profil_languages (
    profil_id BIGINT NOT NULL REFERENCES profil(id) ON DELETE CASCADE,
    languages VARCHAR(255) NOT NULL
);
