ALTER TABLE equipment ADD COLUMN IF NOT EXISTS quantity INT DEFAULT 1 NOT NULL;
ALTER TABLE equipment ADD COLUMN IF NOT EXISTS image_url TEXT;

ALTER TABLE ticket ADD COLUMN IF NOT EXISTS original_price DOUBLE PRECISION;
ALTER TABLE ticket ADD COLUMN IF NOT EXISTS final_price DOUBLE PRECISION;
ALTER TABLE ticket ADD COLUMN IF NOT EXISTS discount_applied BOOLEAN DEFAULT false NOT NULL;
ALTER TABLE ticket ADD COLUMN IF NOT EXISTS discount_rate DOUBLE PRECISION;
ALTER TABLE ticket ADD COLUMN IF NOT EXISTS discount_label VARCHAR(255);
ALTER TABLE ticket ADD COLUMN IF NOT EXISTS payment_status VARCHAR(50) DEFAULT 'PENDING' NOT NULL;
ALTER TABLE ticket ADD COLUMN IF NOT EXISTS stripe_session_id VARCHAR(255);
ALTER TABLE ticket ADD COLUMN IF NOT EXISTS stripe_payment_intent_id VARCHAR(255);

ALTER TABLE stall ADD COLUMN IF NOT EXISTS location VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE stall ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'ASSIGNED' NOT NULL;

ALTER TABLE event ADD COLUMN IF NOT EXISTS meeting_link VARCHAR(255);
ALTER TABLE event ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'UPCOMING' NOT NULL;
ALTER TABLE event ADD COLUMN IF NOT EXISTS nb_tickets INT DEFAULT 0 NOT NULL;
ALTER TABLE event ADD COLUMN IF NOT EXISTS user_id BIGINT;
